name: rasa
description: RASA - Anonymous Curhat + AI Teman Healing. Social healing app (Flutter + Firebase + Gemini AI).
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_riverpod: ^2.5.1
  # Firebase (backend siap pakai, gratis di awal)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.5
  # AI Teman Healing
  google_generative_ai: ^0.4.6
  # Push notification
  onesignal_flutter: ^5.0.0
  # Utils
  timeago: ^3.7.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
